Update setup_ai_toolkit.bat
I tried running this installer recently,  and got 
from diffusers import StableDiffusionPipeline, StableDiffusionXLPipeline, T2IAdapter, DDPMScheduler, \ ImportError: cannot import name 'Lumina2Pipeline' from 'diffusers' (C:\AI\ai-toolkit\venv\Lib\site-packages\diffusers\__init__.py). Did you mean: 'SanaPipeline'?

so these parts have been updated 

REM Upgrade diffusers from GitHub to latest dev (optional but recommended)
pip install --upgrade git+https://github.com/huggingface/diffusers.git

is now added to the end so that the installoation for diffusers and everything else goes through, and after is replaced, a Bat file is also created